#!/bin/sh
#
# description:
#init script for ntop, written by
#branded on freenode
#mbrownnyc everywhere else
#

### BEGIN INIT INFO
# Provides:          ntop
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 3 4 5 6
# Description:       ntop pre-configured by OPTIONS in /etc/sysconfig/ntop
### END INIT INFO

exec="/usr/local/bin/ntop"
prog="ntop"
progname="ntop"
lockfile=/var/lock/subsys/ntop
config=/usr/local/etc/ntopng/ntopng.conf

start() {
echo "Starting $progname:"
echo "   $exec $OPTIONS"
echo
    $exec $OPTIONS
RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
    }

stop() {
    echo -n "Stopping $progname: "
    killproc $prog
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

restart() {
    stop
    start
}

case "$1" in
    start)
        $1
    ;;

    stop)
        $1
    ;;

    restart)
        $1
    ;;

    status)
        status -p /var/run/$prog.pid -l $lockfile $progname
    ;;

    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        exit 1

esac
exit 0
